url: https://ap4l.github.io/
baseurl: 

# Site settings
title: AP4L Project
email: l.bunnell@surrey.ac.uk
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Prof. Nishanth Sastry
  pic: nishanth-sastry.webp
  position: Principal Investigator, Uni of Surrey
  website: https://www.surrey.ac.uk/people/nishanth-sastry
  social:
    - title: twitter
      url: https://twitter.com/nishanthsastry
    - title: linkedin
      url: https://www.linkedin.com/in/nishanthsastry/

- name: Prof. Wendy Moncur
  pic: Wendy.jpg
  position: Co-Investigator, Uni of Strathclyde
  website: https://www.strath.ac.uk/staff/moncurwendyprofessor/
  social:
    - title: twitter
      url: https://twitter.com/wendymoncur
    - title: linkedin
      url: https://www.linkedin.com/in/wendy-moncur-92b2844/

- name: Prof. Steve Schneider
  pic: Steve Schneider.webp
  position: Co-Investigator, Uni of Surrey
  website: https://www.surrey.ac.uk/people/steve-schneider
  social:
    - title: twitter
      url: https://twitter.com/SSchneider2025
    - title: linkedin
      url: https://www.linkedin.com/in/prof-steve-schneider/
      
- name: Dr. Gareth Tyson
  pic: GarethPicture.jpeg
  position: Co-Investigator, QMUL
  website: http://www.eecs.qmul.ac.uk/~tysong/
  social:
    - title: twitter
      url: https://twitter.com/Gareth_Tyson
    - title: linkedin
      url: https://www.linkedin.com/in/gareth-tyson-9472388/
      
- name: Dr. Irina Cojuharenco
  pic: 8.jpg
  position: Co-Investigator, Uni of Surrey
  website: https://www.surrey.ac.uk/people/irina-cojuharenco
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/irina-cojuharenco-19241a89/

- name: Dr. Suparna De
  pic: Suparna De-1262.webp
  position: Co-Investigator, Uni of Surrey
  website: https://www.surrey.ac.uk/people/suparna-de
  social:
    - title: twitter
      url: https://twitter.com/supdey
    - title: linkedin
      url: https://www.linkedin.com/in/suparna-de-unis/

- name: Prof. Helen Treharne
  pic: Helen Treharne.webp
  position: Co-Investigator, Uni of Surrey
  website: https://www.surrey.ac.uk/people/helen-treharne
  social:
    - title: twitter
      url: https://twitter.com/helen_treharne
    - title: linkedin
      url: https://www.linkedin.com/in/helen-treharne/
  
- name: Dr. Catalin Dragan
  pic: Catalin Dragan.jpg
  position: Co-Investigator, Uni of Surrey
  website: https://www.surrey.ac.uk/people/constantin-catalin-dragan
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/constantin-catalin-dragan-ph-d-5611464a/
      
- name: Dr. Karen Renaud
  pic: Karen.png
  position: Co-Investigator, Uni of Strathclyde
  website: https://www.strath.ac.uk/staff/renaudkarendr/
  social:
    - title: twitter
      url: https://twitter.com/drkarenrenaud
    - title: linkedin
      url: https://www.linkedin.com/in/karenrenaud/
      
- name: Prof. Jeff Yan
  pic: Jeff.jpg
  position: Co-Investigator, Uni of Strathclyde
  website: https://pureportal.strath.ac.uk/en/persons/jeff-yan
  social:
    - title: 
      url: https://prof-jeffyan.github.io/

- name: Dr. Diane Morrow
  pic: Diane Morrow.webp
  position: Research Fellow, Uni of Strathclyde
  website: https://pureportal.strath.ac.uk/en/persons/diane-morrow
  social:
    - title: twitter
      url: https://twitter.com/Deepost30
    - title: linkedin
      url: https://www.linkedin.com/in/dr-diane-morrow-93570583/

- name: Prof. Nick Hulbert-Williams
  pic: Nick.png
  position: Co-Investigator, Edge Hill University
  website: https://research.edgehill.ac.uk/en/persons/nicholas-hulbert-williams
  social:
    - title: twitter
      url: https://twitter.com/profnickhw
    - title: linkedin
      url: https://www.linkedin.com/in/nick-hulbert-williams

- name: Lori Wright
  pic: Lori.jpg
  position: Research Assistant, Edge Hill University
  website: https://research.edgehill.ac.uk/en/persons/lorraine-wright
  social: 
    - title: twitter
      url: https://twitter.com/loriwright78
    - title: linkedin
      url: https://www.linkedin.com/in/lorraine-wright-3769971a9/
 
- name: Dr. Adrian Banks   
  pic: adrian-banks.webp
  position: Co-Investigator, Uni of Surrey
  website: https://www.surrey.ac.uk/people/adrian-banks
  social:
    - title: twitter
      url: https://twitter.com/SurreyCogSci

- name: Dr. Michael McGuire
  pic: michael-mcguire.webp
  position: Co-Investigator, Uni of Surrey
  website: https://www.surrey.ac.uk/people/michael-mcguire

- name: Dr. Richard Jones
  pic: Richard Jones.jpg
  position: Co-Investigator, Uni of Edinburgh
  website: https://www.law.ed.ac.uk/people/dr-richard-jones
  social:
    - title: twitter
      url: https://twitter.com/DrRichardJ
    - title: linkedin
      url: https://www.linkedin.com/in/drrichardjones/
      
- name: Dr. Francesca Menichelli
  pic: menichelli f 020518_0213 A5.jpg
  position: Co-Investigator, Uni of Surrey
  website: https://www.surrey.ac.uk/people/francesca-menichelli
  social:
    - title: twitter
      url: https://twitter.com/Fra__Me

- name: Dr. Alice Hutchings
  pic: Alice H.jpeg
  position: Co-Investigator, Uni of Cambridge
  website: https://www.cl.cam.ac.uk/~ah793/
  social:
    - title: twitter
      url: https://twitter.com/message4bob
    - title: linkedin
      url: https://www.linkedin.com/in/ahutchings/

- name: Dr. Arkaitz Zubiaga
  pic: arkaitz.png
  position: Co-Investigator, QMUL
  website: http://eecs.qmul.ac.uk/profiles/zubiagaarkaitz.html
  social:
    - title: twitter
      url: https://twitter.com/arkaitz
    - title: linkedin
      url: https://www.linkedin.com/in/arkaitz/

- name: Dr. Ignacio de Castro
  pic: ignacio.png
  position: Co-Investigator, QMUL
  website: http://www.eecs.qmul.ac.uk/profiles/castroignacio.html
  social:
    - title: twitter
      url: https://twitter.com/Ignactro
    - title: linkedin
      url: https://www.linkedin.com/in/ignacio-de-castro-arribas-44a48117/
      
- name: Dr. Shalini
  pic: Shalini.webp
  position: Research Fellow, Uni of Surrey
  website: https://www.linkedin.com/in/shalini-jangra-67352b70/
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/shalini-jangra-67352b70/
      
- name: Dr. Suleman Lazarus
  pic: Suleman.webp
  position: Research Assistant in Criminology
  website: https://www.lse.ac.uk/social-policy/research/Research-clusters/Mannheim/people/suleman-lazarus
  social:
    - title: twitter
      url: https://twitter.com/DrSLazarus/
    - title: linkedin
      url: https://www.linkedin.com/in/dr-suleman-lazarus-282654129/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ap4lproject
  - title: facebook
    url: https://www.facebook.com/ap4lproject
  - title: linkedin
    url: https://www.linkedin.com/in/ap4l-project-60329023a/

# Postal address (add as many lines as necessary)
address:
  - line: Department of Computer Science
  - line: University of Surrey
  - line: Guildford, GU2 7XH
  
# Build settings
markdown: kramdown
permalink: pretty

# Publications
publications:
  - title: "Privacy Pitfalls of Online Service Terms and Conditions: a Hybrid Approach for Classification and Summarization"
    author: "Lukose, Emilia and De, Suparna and Johnson, Jon"
    Venue: "NLLP"
    paper_url: "https://aclanthology.org/2022.nllp-1.6.pdf"
    pdf:
      - url: "https://aclanthology.org/2022.nllp-1.6.pdf"
        icon: fa fa-file-pdf-o
        
  - title: "Utilizing Weak Supervision to Create S3D: A Sarcasm Annotated Dataset"
    author: "Jordan Painter, Helen Treharne, Diptesh Kanojia"
    Venue: "NLP+CSS"
    paper_url: "https://aclanthology.org/2022.nlpcss-1.22.pdf"
    pdf:
      - url: "https://aclanthology.org/2022.nlpcss-1.22.pdf"
        icon: fa fa-file-pdf-o
         
  - title: "Jettisoning Junk Messaging in the Era of End-to-End Encryption: A Case Study of WhatsApp"
    author: "Pushkal Agarwal, Nishanth Sastry, Gareth Tyson, Damiola Ibosiola,Aravindh Raman"
    Venue: "WWW"
    paper_url: "https://arxiv.org/pdf/2106.05184.pdf"
    pdf:
      - url: "https://arxiv.org/pdf/2106.05184.pdf"
        icon: fa fa-file-pdf-o
        
  - title: "GraphNLI A Graph-based Natural Language Inference Model for Polarity Prediction in Online Debates"
    author: "Vibhor Agarwal, Nishanth Sastry, Anthony P. Young, Sagar Joglekar"
    Venue:  "WWW"
    paper_url: "https://arxiv.org/pdf/2202.08175.pdf"
    pdf:
      - url: "https://arxiv.org/pdf/2202.08175.pdf"
        icon: fa fa-file-pdf-o
        
  - title: "The Web We Weave: Untangling the Social Graph of the IETF"
    author: "Ignacio Castro, Prashant Khare,Gareth Tyson,Matthew Purver,Colin Perkins"
    Venue: " "
    paper_url: "https://ojs.aaai.org/index.php/ICWSM/article/view/19310/19082"
    pdf:
      - url: "https://ojs.aaai.org/index.php/ICWSM/article/view/19310/19082"
        icon: fa fa-file-pdf-o
    
  - title: "Constrained Machine Learning for LoRa Gateway Location Optimisation"
    author: "Abdullahi Abubakar Kutiriko, Tavis Shoree,Nishanth Sastry"
    Venue: " "
    paper_url: "https://dl.acm.org/doi/pdf/10.1145/3570748.3570751"
    pdf:
      - url: "https://dl.acm.org/doi/pdf/10.1145/3570748.3570751"
        icon: fa fa-file-pdf-o
      
  - title: "Design and Evaluation of IPFS: A Storage Layer for the Decentralized Web"
    author: "Dennis Trautweine, Aravindh Raman, Gareth Tyson,Ignacio Castro,Will Scott,Moritz Schubotz,Bela Gipp,Yiannis P saras"
    Venue:  " "
    paper_url: "https://arxiv.org/pdf/2208.05877.pdf"  
    pdf:
      - url: "https://arxiv.org/pdf/2208.05877.pdf"
        icon: fa fa-file-pdf-o    
    
  - title: "What Cookie Consent Notices Do Users Prefer: A Study In The Wild"
    author: "Ashutosh Kumar Singh,Nishanth Sastry,Xuehui Hu,Nisarg Upadhyaya,Arka Seth,Mainack Mondal"
    Venue:  " "
    paper_url: "https://dl.acm.org/doi/pdf/10.1145/3549015.3555675"  
    pdf:
      - url: "https://dl.acm.org/doi/pdf/10.1145/3549015.3555675"
        icon: fa fa-file-pdf-o  
    
  - title: "What Cookie Consent Notices Do Users Prefer: A Study In The Wild"
    author: "David Dang,Christoforos Efstathiou,Dijue Sun,Nisarg Upadhyaya,Haoran Yue,Viji M. Draviam"
    Venue:  " "
    paper_url: "https://rupress.org/jcb/article-pdf/222/5/e202111094/1448667/jcb_202111094.pdf"  
    pdf:
      - url: "https://rupress.org/jcb/article-pdf/222/5/e202111094/1448667/jcb_202111094.pdf"
        icon: fa fa-file-pdf-o
        
  - title: "Mining Composite Spatio-Temporal Lifestyle Patterns from Geotagged Social Data"
    author: "Suparna De,Usamah Jassat,Alex Grace,Wei Wang,Klaus Moessner"
    Venue:  " "
    paper_url: "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9903147"  
    pdf:
      - url: "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9903147"
        icon: fa fa-file-pdf-o   
    
  - title: "Usage Mining of the London Santander Bike-Sharing System"
    author: "Suparna De,Usamah Jassat,Wei Wang,Klaus Moessner"
    Venue:  " "
    paper_url: "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9963751"  
    pdf:
      - url: "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9963751"
        icon: fa fa-file-pdf-o          
     
  - title: "Way back then‚Äù: A Data-driven View of 25+ years of Web Evolution"
    author: "Vibhor Agarwal,Nishanth Sastry"
    Venue:  " "
    paper_url: "https://dl.acm.org/doi/pdf/10.1145/3485447.3512283"  
    pdf:
      - url: "https://dl.acm.org/doi/pdf/10.1145/3485447.3512283"
        icon: fa fa-file-pdf-o
    
  - title: "Toxicity in the Decentralized Web and the Potential for Model Sharing"
    author: "Haris Bin Zia,Aravindh Raman,ignacio Castro,Nishanth Sastry,Ishaku Hassan Anaobi,emiliano De Cristofaro,Gareth Tyson"
    Venue:  " "
    paper_url: "https://dl.acm.org/doi/pdf/10.1145/3530901"  
    pdf:
      - url: "https://dl.acm.org/doi/pdf/10.1145/3530901"
        icon: fa fa-file-pdf-o
     
  - title: "Lessons from the age of user-generated content for the age of AI-generated content"
    author: "Prof. Nishanth Sastry"
    Venue: "https://wsl.iiitb.ac.in/cikm-2023-ekgllm-invited-talks/"
    paper_url: ""
    pdf:
      - url: "https://wsl.iiitb.ac.in/cikm-2023-ekgllm-invited-talks/"
        icon: fa fa-file-pdf-o

        
